version: "3"

services:
  # backend:
  #   context: ./server
  #   ports:
  #     - "5555:5555"
  #   volumes: 
  #     - ./server:/go/src/app
  #   depends_on:
  #     - database
  #   environment:
  #     DATABASE_URL: "file:/database/sqlite3.db"

  database:
    image: keinos/sqlite3:latest
    restart: always
    container_name: sqlite3
    volumes:
      - ./database/:/database/
    ports:
      - 7777:7777
