version: "3"

services:
  database:
    build:
      context: ./database
    volumes:
      db: /usr/www/mysql
    ports:
      - "7777:7777"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ragnarok_db
        MYSQL_USER: ragnarok
        MYSQL_PASSWORD: ragnarok
    networks:
      - local

volumes:
  db:

networks:
  local:
