version: "3"

services:
  # backend:
  #   build:
    #   context: ./server
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - database
 
  database:
    build:
      context: ./database
    volumes:
      - ./database:/usr/src/app
    ports:
      - "7777:7777"
